# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
on:
  push:
    branches: ["master"]
    paths:
      - "**.go"
  pull_request:
    branches: ["master"]
    paths:
      - "**.go"

jobs:
  build:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: InstallDependencies
        run: go get .

      - name: Build
        run: go build -o bad-word-service .

      - name: Commit and push if it changed
        run: |
          git config --global user.email "mekavehamichlol@gmail.com"
          git config --global user.name "mekavehamichlolay"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated build output"
          git push https://github.com/mekavehamichlolay/bad-word-service.git
